add a bunch of bazel flags

diff --git a/.buildkite/gpu_pipeline.yml b/.buildkite/gpu_pipeline.yml
--- a/.buildkite/gpu_pipeline.yml
+++ b/.buildkite/gpu_pipeline.yml
@@ -53,11 +53,35 @@ steps:
       export LD_LIBRARY_PATH="`pwd`/bazel-bin/test/llama.runfiles/pypi_nvidia_cuda_runtime_cu12/site-packages/nvidia/cuda_runtime/lib:\$LD_LIBRARY_PATH"
       export PATH="`pwd`/bazel-bin/test/llama.runfiles/pypi_nvidia_cuda_nvcc_cu12/site-packages/nvidia/cuda_nvcc/bin:\$PATH"
       export TF_CPP_MIN_LOG_LEVEL=0
+
+      BAZEL_BUILD_FLAGS=()
+      BAZEL_BUILD_FLAGS+=(--define=no_aws_support=true)
+      BAZEL_BUILD_FLAGS+=(--define=no_gcp_support=true)
+      BAZEL_BUILD_FLAGS+=(--define=no_hdfs_support=true)
+      BAZEL_BUILD_FLAGS+=(--define=no_kafka_support=true)
+      BAZEL_BUILD_FLAGS+=(--define=no_ignite_support=true)
+      BAZEL_BUILD_FLAGS+=(--define=grpc_no_ares=true)
+
+      BAZEL_BUILD_FLAGS+=(--define=llvm_enable_zlib=false)
+
+      BAZEL_BUILD_FLAGS+=(--verbose_failures)
+      BAZEL_BUILD_FLAGS+=(--cxxopt=-std=c++17 --host_cxxopt=-std=c++17)
+      BAZEL_BUILD_FLAGS+=(--cxxopt=-DTCP_USER_TIMEOUT=0)
+      BAZEL_BUILD_FLAGS+=(--check_visibility=false)
+      BAZEL_BUILD_FLAGS+=(--experimental_cc_shared_library)
+
+      mkdir .eqsat-tmp
+      export TMPDIR="`pwd`/.eqsat-tmp"
+      export TMP=$TMPDIR
+      export TEMP=$TMPDIR
+      BAZEL_BUILD_FLAGS+=(--action_env=TMP=\$TMPDIR --action_env=TEMP=\$TMPDIR --action_env=TMPDIR=\$TMPDIR --sandbox_tmpfs_path=\$TMPDIR)
+      BAZEL_BUILD_FLAGS+=(--config=cuda)
+
       CARGO_BAZEL_REPIN=true HERMETIC_PYTHON_VERSION="3.12" .local/bin/bazel --output_user_root=`pwd`/.baztmp run --repo_env CUDA_DIR --repo_env XLA_FLAGS --action_env XLA_FLAGS --repo_env TF_CPP_MIN_LOG_LEVEL --action_env TF_CPP_MIN_LOG_LEVEL //builddeps:requirements.update || echo "no req update"
       # HERMETIC_PYTHON_VERSION="3.12" .local/bin/bazel --output_user_root=`pwd`/.baztmp test --repo_env CUDA_DIR --repo_env XLA_FLAGS --action_env XLA_FLAGS --repo_env TF_CPP_MIN_LOG_LEVEL --action_env TF_CPP_MIN_LOG_LEVEL --test_output=errors //test/... || echo "fail1"
       # find `pwd`/bazel-bin/test/llama.runfiles > finds.txt
       # HERMETIC_PYTHON_VERSION="3.12" .local/bin/bazel --output_user_root=`pwd`/.baztmp test --repo_env CUDA_DIR --repo_env XLA_FLAGS --action_env XLA_FLAGS --repo_env TF_CPP_MIN_LOG_LEVEL --action_env TF_CPP_MIN_LOG_LEVEL --cache_test_results=no -s //test:bench_vs_xla || echo "fail2"
-      HERMETIC_PYTHON_VERSION="3.12" .local/bin/bazel --output_user_root=`pwd`/.baztmp test --repo_env CUDA_DIR --repo_env XLA_FLAGS --action_env XLA_FLAGS --repo_env TF_CPP_MIN_LOG_LEVEL --action_env TF_CPP_MIN_LOG_LEVEL --cache_test_results=no -s --config=cuda //test:llama || echo "fail3"
+      HERMETIC_PYTHON_VERSION="3.12" .local/bin/bazel --output_user_root=`pwd`/.baztmp test --repo_env CUDA_DIR --repo_env XLA_FLAGS --action_env XLA_FLAGS --repo_env TF_CPP_MIN_LOG_LEVEL --action_env TF_CPP_MIN_LOG_LEVEL --cache_test_results=no -s \${BAZEL_BUILD_FLAGS[@]} //test:llama || echo "fail3"
       HERMETIC_PYTHON_VERSION="3.12" bazel-bin/test/llama
       cat bazel-out/*/testlogs/test/llama/test.log
     artifact_paths:
