[CI] Add step in GB-25 tests to show global communications

diff --git a/.github/workflows/test-gb-25.yml b/.github/workflows/test-gb-25.yml
--- a/.github/workflows/test-gb-25.yml
+++ b/.github/workflows/test-gb-25.yml
@@ -184,10 +184,39 @@ jobs:
           julia --project --color=yes -e "using MPI; MPI.install_mpiexecjl(; destdir=\"${MPIEXECJL_DIR}\")"
           echo "${MPIEXECJL_DIR}" >> "${GITHUB_PATH}"
         working-directory: ${{ env.GB25_DIR }}
+      - name: Compile GB-25 simulation
+        timeout-minutes: 30
+        run: |
+          export XLA_FLAGS='--xla_dump_to=${{ env.GB25_DIR }}/xla_dump_compile'
+          timeout --signal=TERM --verbose 29m mpiexecjl -np 1 julia --color=yes --project -O0 --startup-file=no --threads=16 --compiled-modules=strict sharding/sharded_baroclinic_instability_simulation_compile.jl
+        working-directory: ${{ env.GB25_DIR }}
+      - name: Show remaining collective operations
+        timeout-minutes: 10
+        shell: bash
+        run: |
+          OK="true"
+          for OP in all-to-all all-gather all-reduce; do
+              COLLECTIVES=$(find . -name 'optimised_sharded_baroclinic_instability*.xla' -exec grep --with-filename --line-number --extended-regexp "${OP}" '{}' \;)
+              NUM_COLLECTIVES=$(echo "${COLLECTIVES}" | wc -l | xargs)
+              if [[ -n "${COLLECTIVES}" ]]; then
+                  MSG="There are ${NUM_COLLECTIVES} remaining ${OP} operations"
+                  echo "::error title=Remaining ${OP} Operations:: ${MSG}"
+                  echo
+                  echo "----------"
+                  echo "${COLLECTIVES}"
+                  echo "----------"
+                  if [[ "${OP}" == "all-to-all" && ${NUM_COLLECTIVES} -gt 0 ]] || [[ "${OP}" == "all-gather" && ${NUM_COLLECTIVES} -gt 0 ]] || [[ "${OP}" == "all-reduce" && ${NUM_COLLECTIVES} -gt 0 ]]; then
+                      OK="false"
+                  fi
+              fi
+          done
+          if [[ "${OK}" == "false" ]]; then
+              exit 1
+          fi
       - name: Run GB-25 simulation
         timeout-minutes: 60
         run: |
-          export XLA_FLAGS='--xla_dump_to=${{ env.GB25_DIR }}/xla_dump'
+          export XLA_FLAGS='--xla_dump_to=${{ env.GB25_DIR }}/xla_dump_run'
           timeout --signal=TERM --verbose 59m mpiexecjl -np 1 julia --color=yes --project -O0 --startup-file=no --threads=16 --compiled-modules=strict sharding/sharded_baroclinic_instability_simulation_run.jl
         working-directory: ${{ env.GB25_DIR }}
       - name: Test correctness in GB-25 code
@@ -212,7 +241,7 @@ jobs:
         if: ${{ !cancelled() }}
         with:
           name: 'simulation-xla-dump-${{ env.ARTIFACT_INDEX }}'
-          path: '${{ env.GB25_DIR }}/**/xla_dump'
+          path: '${{ env.GB25_DIR }}/**/xla_dump*'
           retention-days: 90
           overwrite: false
       - name: Upload XLA profiler traces
